### ISSUE TITLE
Apply a critical fix to TensorFlow 1.13

### ISSUE THREAD

**Issue by hanyucui** [AnacondaRecipes/tensorflow_recipes#13]
Hi,

We are planning to upgrade `tensorflow-gpu` from 1.12.0 to 1.13.1. However, 1.13.1 is currently missing a critical fix, and the TensorFlow team is not going to include it any time soon. Without this fix, we won't be able to use Horovod with TensorFlow on multiple GPUs, and this is an important use case for us. I am wondering if you could cherry-pick tensorflow/tensorflow@a427c13, apply it to 1.13.1, and re-publish the package. 

Related discussions:
- tensorflow/tensorflow#24303
- tensorflow/tensorflow#24461
- horovod/horovod#602

Let me know if you have any questions. Thanks in advance!

**Comment by msarahan** [comment]
Tensorflow builds entail several hours of work.  This request is large enough that we'd require some package build service agreement.  Please contact sales@anaconda.com if you're interested.  Otherwise, you're at the mercy of the Tensorflow team's release schedule, or you need to build your own packages.
