### ISSUE TITLE
tensorflow-gpu not using SSE4 or AVX instructions

### ISSUE THREAD

**Issue by jakirkham** [AnacondaRecipes/tensorflow_recipes#6]
Tensorflow issued some warnings about not using SSE4 or AVX instructions. Figured I'd follow up on this. Though this is the GPU package, so maybe it doesn't matter. Warnings below.

```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
```

**Comment by jjhelmus** [comment]
Tensorflow does not support dynamic dispatch of code pathways.  Therefore if you build the package to take advantage of SSE4 or AVX it will not run on CPUs without these extensions.  In order to support a large user base our minimum CPU architecture for the `linux-64` platform is `nocona`.  This micro-architecture does not include the SSE4 or AVX extensions.

**Comment by jakirkham** [comment]
Right, just thought that `-mtune=haswell` was also being used so that it would take advantage of a Haswell processor if possible. Meaning these instructions would be available and used. Is that not the case?

**Comment by jjhelmus** [comment]
We are passing `-mtune=haswell` [to the build](https://github.com/AnacondaRecipes/tensorflow_recipes/blob/master/tensorflow-base-cpu/build.sh#L55) but I don't believe the logic in cpu_feature_guard is aware of this.  For better performance on CPU use the `tensorflow-mkl` package which uses the MKL-DNN library for dynamic dispatch.

**Comment by mingwandroid** [comment]
`-mtune=haswell` only affects the instruction scheduler so that it is most closely aligned with the pipeline of that CPU. It has no bearing on which instructions are emitted and therefore the choice of that flag is guided by market share.

`-mcpu=` is the one that changes what instructions get used.

**Comment by jakirkham** [comment]
What's the impact of this on codes that do support dynamic architecture detection (e.g. `openblas`)?

**Comment by mingwandroid** [comment]
If `-mcpu=*` has any impact on the build then it should be masked off from the build flags. I'm almost certain that it doesn't since `openblas` adds its own `-mcpu=*` later on in the flags depending on the CPU it's compiling for and that'll override our value anyway.
